#!/usr/bin/env bun
// Registers this wallet's unshielded NIGHT UTXOs for DUST generation.
// Run this ONCE, before deploy-contract.ts, on any wallet that has never
// deployed on this network.
//
//   MIDNIGHT_NETWORK_ID=preview \
//   MIDNIGHT_STORAGE_PASSWORD=<your-secret> \
//   MIDNIGHT_WALLET_SEED=<seed> \
//   bun run deploy/register-dust.ts
//
// WHY THIS EXISTS
//
// A deploy against a freshly funded wallet fails with:
//
//   Wallet.InsufficientFunds: Insufficient Funds: could not balance dust
//
// That error does NOT mean the wallet is empty. On Midnight, transaction
// fees are paid in DUST, and DUST is not something a faucet sends you: it
// is *generated* by NIGHT that has been explicitly registered for dust
// generation. A wallet can hold plenty of NIGHT and still have zero
// spendable DUST, which is exactly this failure.
//
// The registration is its own on-chain transaction, separate from the
// deploy. @effectstream/midnight-contracts exposes `registerNightForDust`
// for it, whose own doc comment reads: "Register unshielded Night UTXOs
// for dust generation. This is required before the wallet can pay
// transaction fees." Internally it looks for NIGHT UTXOs whose
// `meta.registeredForDustGeneration` is false, submits the registration,
// and waits for DUST to actually appear.
//
// `deployMidnightContract` never calls it. Its wallet setup
// (`buildWalletAndWaitForFunds`) only waits on the *shielded* balance and
// ignores the dust balance entirely, so on a funded-but-unregistered
// wallet it reports success and hands a wallet that cannot pay fees
// straight to the deploy.
//
// Registration state lives on-chain, on the UTXO. Once this script
// succeeds, the normal deploy works and this does not need to run again
// for the same wallet and NIGHT.
//
// SECOND FAILURE MODE, same error text: if the wallet sits idle for ~1h,
// the merkle roots its DUST UTXOs need get pruned from the node's
// root_history. The balance still reads fine but nothing is spendable.
// The fix there is not registration, it is freshness — resync and submit
// promptly rather than leaving a wallet warm for an hour between steps.
// See the Midnight team's answer:
// https://forum.midnight.network/t/preprod-custom-error-173-wallet-insufficientfunds-could-not-balance-dust-despite-large-dust-balance-now-on-shared-bridge-claimer/1164
import { setNetworkId } from "@midnight-ntwrk/midnight-js-network-id";
import type { NetworkId } from "@midnightntwrk/wallet-sdk-abstractions";
import {
  buildWalletAndWaitForFunds,
  registerNightForDust,
} from "@effectstream/midnight-contracts";
// Importing this runs its env checks: MIDNIGHT_NETWORK_ID and
// MIDNIGHT_STORAGE_PASSWORD are both required and both fail closed.
import { midnightNetworkConfig } from "./network-config.js";
import { safeNetworkConfigForLogging, withSeedRedaction } from "./redact-seed.js";

console.log("Registering NIGHT for DUST generation. Network config:", safeNetworkConfigForLogging(midnightNetworkConfig));

const networkId = midnightNetworkConfig.id as NetworkId.NetworkId;
const networkUrls = {
  id: midnightNetworkConfig.id,
  indexer: midnightNetworkConfig.indexer,
  indexerWS: midnightNetworkConfig.indexerWS,
  node: midnightNetworkConfig.node,
  proofServer: midnightNetworkConfig.proofServer,
};

async function main(): Promise<boolean> {
  if (!midnightNetworkConfig.walletSeed) {
    throw new Error(
      "No wallet seed. Set MIDNIGHT_WALLET_SEED (or MIDNIGHT_WALLET_MNEMONIC) — " +
        "and use a disposable wallet: the deploy dependency logs the seed, see docs/RED_TEAM_ROUND_4.md.",
    );
  }

  // deployMidnightContract does this internally before building a wallet;
  // building one outside that call means doing it here too.
  setNetworkId(networkId);

  const walletResult = await buildWalletAndWaitForFunds(
    networkUrls,
    midnightNetworkConfig.walletSeed,
    networkId,
  );

  // The address that matters here is the UNSHIELDED one: DUST is generated by
  // unshielded NIGHT, so this is the address the faucet must have funded. The
  // dependency logs the shielded coin key and the dust address but not this
  // one, which makes "did I just register the wallet I actually funded?"
  // unanswerable from its output alone.
  console.log(`Unshielded address (this is the one that must hold NIGHT): ${walletResult.unshieldedAddress}`);

  // Returns true when dust is available afterwards — either because it
  // registered NIGHT and dust arrived, or because dust was already there.
  return registerNightForDust(walletResult);
}

withSeedRedaction(main)
  .then((ok) => {
    if (ok) {
      console.log("DUST is available. `bun run deploy/deploy-contract.ts` should now get past fee balancing.");
      process.exit(0);
    }
    console.error(
      "Registration did not result in spendable DUST.\n" +
        "  - No unshielded NIGHT in this wallet? Fund it from the faucet first (NIGHT, not shielded tokens).\n" +
        "  - Already registered but DUST still 0? Generation is proportional to NIGHT held and takes time — wait, then re-run.\n" +
        "  - Check the proof server is reachable at " + midnightNetworkConfig.proofServer + " (fee balancing needs it).",
    );
    process.exit(1);
  })
  .catch((e: unknown) => {
    console.error("NIGHT->DUST registration failed:", e);
    process.exit(1);
  });
